baseURL: "https://jack-kin.github.io/"
title: Kin's Blog
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

taxonomies:
  category: categories
  tag: tags

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Hello
  description: "Kin's Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Kin
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  ShowlastMod: true

  comments: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon_io/favicon.ico"
    favicon16x16: "favicon_io/favicon-16x16.png"
    favicon32x32: "favicon_io/favicon-32x32.png"
    apple_touch_icon: "favicon_io/apple-touch-icon.png"
    # safari_pinned_tab: "favicon_io/android-chrome-192x192.png"

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Zhejian Jin
    subtitle: "Master Student at Columbia University"
    imageUrl: "profile.jpg"
    imageWidth: 150
    imageHeight: 150
    imageTitle: cool man
    buttons:
      - name: Post
        url: posts
      - name: About
        url: about
      - name: Resume
        url: ZhejianJin_resume_20220913.pdf

  # home-info mode
  homeInfoParams:
    Title: "Welcome"
    Content: Welcome to my blog

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/Jack-Kin/"
    - name: linkedin
      url: "https://www.linkedin.com/in/zhejian-jin/"
    - name: instagram
      url: "https://www.instagram.com/jackkin23/"
    - name: email
      url: "mailto:zj2324@columbia.edu"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/jack-kin.github.io/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 1
    - identifier: home
      name: Home
      url: /
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: archives 
      name: Archives
      url: /archives/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
    - identifier: about
      name: About
      url: /about/
      weight: 6
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: vim

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true